package com.sumedh.twinmind.app.domain.model

import java.time.OffsetDateTime

data class Meeting(
    val id: Long = 0, // Auto-generated by Room
    val title: String,
    val createdAt: OffsetDateTime
)