package com.sumedh.twinmind.app.domain.model

data class Transcript(
    val id: Long = 0, // Auto-generated by Room
    val meetingId: Long,
    val text: String,
    val timestamp: Long // e.g., milliseconds from the start of the meeting
)